<a href="https://colab.research.google.com/github/samsaraswat010-dotcom/Datascience-p1/blob/main/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from pandas import Series,DataFrame
import pandas as pd

In [ ]:
obj = Series([3,6,9,12])
obj

0     3
1     6
2     9
3    12
dtype: int64

In [ ]:
obj.values

array([ 3,  6,  9, 12])

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
ww2_cas = Series([8700000,4300000,3000000,2100000,400000],index=['USSR','Germany','China','Japan','USA'])

#Show
ww2_cas

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64

In [ ]:
ww2_cas.loc['USA']

np.int64(400000)

In [ ]:
ww2_cas.iloc[4]

np.int64(400000)

In [ ]:
ww2_cas_dic={8700000:'USSR',4300000:'Germany'}
ww2_cas_dic

SyntaxError: invalid syntax (2226073503.py, line 1)

In [ ]:
list1=[78, 850, 83, 68, 91]

In [ ]:
list2 =["Laptop","Srijan","Sachin","Rohit","Sambhav"]

In [ ]:
marks=Series(list1,index=list2)
marks

Laptop      78
Srijan     850
Sachin      83
Rohit       68
Sambhav     91
dtype: int64

In [ ]:
ww2_cas['USA']

np.int64(400000)

In [ ]:
ww2_cas[ww2_cas>4000000]

USSR       8700000
Germany    4300000
dtype: int64

In [ ]:
#Can treat Series as ordered dictionary

#Check if USSR is in Series
'USSR' in ww2_cas

True

In [ ]:
#Can convert Series into Python dictionary
ww2_dict = ww2_cas.to_dict()

#Show
ww2_dict

{'USSR': 8700000,
 'Germany': 4300000,
 'China': 3000000,
 'Japan': 2100000,
 'USA': 400000}

In [ ]:
#Can convert back into a Series
WW2_Series = Series(ww2_dict)

In [ ]:
#Show
WW2_Series

In [ ]:
#Passing a dictionary the index will have the dict keys in order
countries = ['China','Germany','Japan','USA','USSR','Argentina']

In [ ]:
#Lets redefine a Series
obj2 = Series(ww2_dict,index=countries)

In [ ]:
#Show
obj2

In [ ]:
#We can use isnull and notnull to find missing data
pd.isnull(obj2)

#obj2.isnull()

In [ ]:
#Same for the opposite
pd.notnull(obj2)

#obj2.notnull()

In [ ]:
#Lets see the ww2 Series again
WW2_Series

In [ ]:
#Lets check our Series with Argentine again
obj2

In [ ]:
#Now we can add and pandas automatically aligns data by index
WW2_Series + obj2

In [ ]:
#We can give Series names
obj2.name = "World War 2 Casualties"

In [ ]:
#Show
obj2

In [ ]:
#We can also name index
obj2.index.name = 'Countries'

In [ ]:
#Show
obj2

In [ ]:
#Next we'll learn DataFrames!